edge right
columns 60                                                                                

background_opacity 0.5
background_blur 10

# behavior                                                                                                                               
hide_on_focus_loss yes                                    
start_as_hidden yes                                                                                                                      
grab_keyboard yes
                                                                                                                                                                                                                                                                                                                          
# startup_session none                                  
                               