gui:
  theme:
    activeBorderColor: ["#58b0b8", "bold"]
    inactiveBorderColor: ["#5a7880"]
    searchingActiveBorderColor: ["#e8c888", "bold"]
    optionsTextColor: ["#5090b0"]
    selectedLineBgColor: ["#263d42"]
    inactiveViewSelectedLineBgColor: ["#1b2f34"]
    cherryPickedCommitFgColor: ["#a890c0"]
    cherryPickedCommitBgColor: ["#263d42"]
    markedBaseCommitFgColor: ["#e8c888"]
    markedBaseCommitBgColor: ["#263d42"]
    unstagedChangesColor: ["#e878a8"]
    defaultFgColor: ["#e4ebe4"]
  nerdFontsVersion: "3"
  border: "rounded"
  showFileTree: true
  showCommandLog: true
  showBottomLine: true
  showListFooter: true
  showBranchCommitHash: false
  showFileIcons: true
  mainPanelSplitMode: "flexible"
  filterMode: "fuzzy"
  sidePanelWidth: 0.3333
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  language: "auto"

git:
  autoFetch: true
  autoRefresh: true
  autoStageResolvedConflicts: true
  overrideGpg: false
  disableForcePushing: false
  fetchAll: true
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  log:
    order: "topo-order"
    showGraph: "always"

os:
  editPreset: "nvim"
  editInTerminal: true

promptToReturnFromSubprocess: false
confirmOnQuit: false
disableStartupPopups: true
