foreground            #e4ebe4
background            #13222c
selection_foreground  #e4ebe4
selection_background  #263d42

cursor                #eef4ec
cursor_text_color     #13242a

url_color             #5090b0

# splits, tab bar
active_tab_foreground    #13242a
active_tab_background    #5090b0
inactive_tab_foreground  #8098a0
inactive_tab_background  #1b2f34
tab_bar_backround        #13242a

active_border_color      #e878a8
inactive_border_color    #253d42
bell_border_color        #e8c888

# normal colors
color0  #13242a                                                                                                                        
color1  #e878a8                                                                                                                        
color2  #78b098
color3  #e8c888                                                                                                                        
color4  #5090b0 
color5  #a890c0                                                                                                                        
color6  #58b0b8
color7  #e4ebe4

# bright colors
color8  #5a7880
color9  #e878a8                                                                                                                        
color10 #78b098
color11 #e8c888                                                                                                                        
color12 #5090b0 
color13 #a890c0
color14 #58b0b8                                                                                                                        
color15 #f6faf4

# extended
color16 #e89878
color17 #78786a